version: '3'

services:
  postgres:
    container_name: zero-postgres
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=zero_test
      - POSTGRES_PASSWORD=zero_test
      - POSTGRES_DB=zero_test
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - './data:/var/lib/postgresql/data'
      - './testdata:/testdata'