version: '3'

services:
  helloworld:
    image: "strm/helloworld-http"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.helloworld-loadbalancer-test.rule=Host(`helloworld.localhost`)"
      - "traefik.http.routers.helloworld-loadbalancer-test.entrypoints=web"

networks:
  default:
    external:
      name: gateway_default
